name: Build and Publish NuGet Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

# Define the SQL password at the top of the file - used in multiple places
env:
  SQL_PASSWORD: "SecretsAreHandicapped@2025!"

  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    services:
      sql:
        image: mcr.microsoft.com/mssql/server:2019-CU16-ubuntu-20.04
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: "${{ env.SQL_PASSWORD }}"
        ports:
          - 1433:1433
        options: >-
          --health-cmd="(/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"SecretsAreHandicapped@2025!\" -Q \"SELECT 1\" && exit 0) || exit 1"
          --health-interval 15s
          --health-timeout 10s
          --health-retries 10
          --health-start-period 120s

      
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Ensures all history and tags are fetched for versioning

    - name: Wait for SQL Server to be ready
      run: |
        for i in {1..10}; do
        if [ "$(docker inspect -f {{.State.Health.Status}} sql)" == "healthy" ]; then
         echo "SQL Server is ready."
         break
        fi
        echo "Waiting for SQL Server to be ready..."
        sleep 10
        done
        if [ "$(docker inspect -f {{.State.Health.Status}} sql)" != "healthy" ]; then
        echo "SQL Server failed to initialize."
        exit 1
        fi
        
    - name: Set up SQL Test DB
      run: |
         # Wait for SQL Server to initialize
          sleep 60
          # Create the test database
          docker exec -it sql /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "SecretsAreHandicapped@2025!" \
            -Q "CREATE DATABASE SequentialIdTests"
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          8.0.x
    
    - name: Create Test Database
      run: |
        # Install SQL Server client tools
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev
        
        # Create the test database
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${{ env.SQL_PASSWORD }}" -Q "CREATE DATABASE SequentialIdTests"
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      env:
        ConnectionStrings__testdb: "Server=localhost;Database=SequentialIdTests;User Id=sa;Password=${{ env.SQL_PASSWORD }};TrustServerCertificate=True;"
    
    - name: Pack
      run: dotnet pack ObjectIdentity/ObjectIdentity.csproj --configuration Release --no-build --output ./nupkgs
    
    - name: Push to NuGet.org
      # Only run this step when pushing to main branch (not for PRs)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate