name: Build and Publish NuGet Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

# Define the SQL password at the top of the file - used in multiple places
env:
  # SECURITY: Using hardcoded credentials for ephemeral test container only.
  # This container is isolated and destroyed after tests complete.
  # NOT a security risk as it's never exposed beyond the CI environment.
  # nosec or #pragma: allowlist secret
  SA_PASSWORD: "SecretsAreHandicapped@2025"
  ACCEPT_EULA: Y
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    services:
      sql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        # Health check ensures SQL Server is ready before tests run
        options: >-
          --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"SecretsAreHandicapped@2025!\" -Q \"SELECT 1\" || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 10s
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Ensures all history and tags are fetched for versioning
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          8.0.x
    
    - name: Create Test Database
      run: |
        # Install SQL Server client tools
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev
        
        # Create the test database
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${{ env.SQL_PASSWORD }}" -Q "CREATE DATABASE SequentialIdTests"
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      env:
        ConnectionStrings__testdb: "Server=localhost;Database=SequentialIdTests;User Id=sa;Password=${{ env.SQL_PASSWORD }};TrustServerCertificate=True;"
    
    - name: Pack
      run: dotnet pack ObjectIdentity/ObjectIdentity.csproj --configuration Release --no-build --output ./nupkgs
    
    - name: Push to NuGet.org
      # Only run this step when pushing to main branch (not for PRs)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate